use bioinformatics_algorithms::seq_analysis::protein::ProteinSeqAnalysis;
fn main() {
    let res = ProteinSeqAnalysis::analyze(b"MAEGEITTFTALTEKFNLPPGNYKKPKLLYCSNGGHFLRILPDGTVDGTRDRSDQHIQLQLSAESVGEVYIKSTETGQYLAMDTSGLLYGSQTPSEECLFLERLEENHYNTYTSKKHAEKNWFVGLKKNGSCKRGPRTHYGQKAILFLPLPV");
    println!("{}", res);
}
